name: Daily Scraping Workflow

on:
  schedule:
    # Runs at 1:15 AM UTC every day
    - cron: '15 1 * * *'
  workflow_dispatch:  # This line adds the manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace '3.x' with the specific version if needed

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pandas # Add other dependencies if needed

      - name: Run scraping script
        run: python pre_processing.py 
